sonar.projectKey=WinnyKing57_WinnyKing57_73786311-7932-4b1e-84f8-fdace9a2e527
sonar.projectName=WinnyKing57

# Depot de profil GitHub : le seul fichier suivi est README.md.
sonar.sources=.
sonar.sourceEncoding=UTF-8
